# Use baseimage-docker which is a modified Ubuntu specifically for Docker
# https://hub.docker.com/r/phusion/baseimage
# https://github.com/phusion/baseimage-docker
#FROM phusion/baseimage:0.11
FROM phusion/baseimage:jammy-1.0.0

# Use baseimage-docker's init system
CMD ["/sbin/my_init"]


# Update and install packages
RUN apt update && apt -y upgrade && apt -y install \
    wget \
    sudo

RUN apt -y install \
    build-essential \
    python3-dev 

ARG INSTALL_PATH=/opt/gryphon

RUN mkdir $INSTALL_PATH

WORKDIR $INSTALL_PATH

RUN wget https://gitlab.nps.edu/monterey-phoenix/user-interfaces/gryphon/-/raw/master/install_mp.bash

RUN chmod u+x $INSTALL_PATH/install_mp.bash 

RUN yes | bash $INSTALL_PATH/install_mp.bash ubuntu

