FROM ubuntu@sha256:9a0bdde4188b896a372804be2384015e90e3f84906b750c1a53539b585fbbe7f

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y \
     build-essential \
     libc6-dev-i386 \
     csh \
     python3-pip \
     python3-pyqt5

# Qt requires non-root
RUN adduser --quiet --disabled-password mp_user && usermod -a -G audio mp_user
USER mp_user:audio
RUN pip3 install --upgrade pip
RUN pip3 install \
     opencv-python-headless \
     PySide6 \
     pyqtdarktheme

WORKDIR /opt

COPY minimum_qt_demo.py /opt

# Qt environment
ENV QT_DEBUG_PLUGINS=1
